# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Core'
pod 'Firebase'
target 'KeiserTony_Proof' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

end
